name: fastsd-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=23.3
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pip:
      - accelerate==0.23.0
      - diffusers==0.21.4
      - transformers==4.34.0
      - PyQt5==5.15.10
